#!/bin/bash
set -e

psql -v ON_ERR_STOP=1 --username $POSTGRES_USER --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER drakoapi WITH ENCRYPTED PASSWORD '${DRAKO_API_DB_PASSWORD}';
CREATE USER drakosuper WITH ENCRYPTED PASSWORD '${POSTGRES_PASSWORD}';
CREATE DATABASE drakoapi WITH OWNER drakoapi ENCODING='UTF-8' LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8';
EOSQL
